# Generated by Django 5.0.3 on 2024-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='card',
            field=models.BooleanField(default=False),
        ),
    ]
