# Generated by Django 5.0.3 on 2024-06-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0002_phone_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='card',
            new_name='cart',
        ),
    ]
