# Generated by Django 5.0.3 on 2024-06-28 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones_app', '0003_rename_card_phone_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='phones_app.brand'),
        ),
    ]
